# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Product_notification_bar"
client_id = "5a66c7b4dbe06298dadacdfaa8167e7f"
application_url = "https://turning-alien-grants-utc.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_orders"

[auth]
redirect_urls = [
  "https://turning-alien-grants-utc.trycloudflare.com/auth/callback",
  "https://turning-alien-grants-utc.trycloudflare.com/auth/shopify/callback",
  "https://turning-alien-grants-utc.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "storeapp-dev.myshopify.com"
